In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import wilcoxon
import itertools
import sys
sys.path.insert(0, os.path.dirname(os.getcwd()))
import liset_tk.lists_sessions as lists_sessions
# Set style
sns.set_style("whitegrid")
# plt.rcParams.update({'font.size': 12})
plt.rcParams['svg.fonttype'] = 'none'

# LOAD METRICS

In [ ]:
# Load Dutta Data
results_path = os.path.join("spikes", "all_networks_metrics_dutta.csv")

if os.path.exists(results_path):
    dutta_df = pd.read_csv(results_path)
    print(f"Loaded {len(dutta_df)} rows from {results_path}")
    
    # Preprocessing
    # Rename ADAPT to Adapt for consistency
    if "ADAPT" in dutta_df.columns:
        dutta_df.rename(columns={"ADAPT": "Adapt"}, inplace=True)
        
    print("Columns:", dutta_df.columns.tolist())
    print("Threshold:", sorted(dutta_df["Threshold"].unique()))
    
    display(dutta_df.head())
else:
    print(f"File not found: {results_path}. Please run process_live_spikes.py first.")

Loaded 78 rows from spikes\all_networks_metrics_dutta.csv
Columns: ['Session', 'Channel', 'Threshold', 'TP', 'FP', 'FN', 'Precision', 'Recall', 'F1', 'Mean_Latency', 'Num_Spikes', 'Num_Ripples']
Threshold: [3.0, 4.0, 5.0, 6.0, 7.0, 8.0]

,Session,Channel,Threshold,TP,FP,FN,Precision,Recall,F1,Mean_Latency,Num_Spikes,Num_Ripples
0,2025-09-24_17-38-17,13,3.0,11,564,4,0.019130,0.733333,0.037288,35.321212,577,15
1,2025-09-24_16-29-07,5,3.0,25,497,15,0.047893,0.625000,0.088968,9.848000,528,40
2,2025-09-22_17-55-26,26,3.0,130,251,55,0.341207,0.702703,0.459364,16.261795,385,185
3,2025-09-23_15-50-26,28,3.0,94,333,45,0.220141,0.676259,0.332155,11.527305,430,139
4,2025-09-24_10-24-40,30,3.0,57,502,35,0.101968,0.619565,0.175115,16.625731,564,92

In [3]:
# Load Data
results_path = os.path.join("spikes", "all_networks_metrics_ripplenet.csv")

if os.path.exists(results_path):
    rippleNet_df = pd.read_csv(results_path)
    print(f"Loaded {len(rippleNet_df)} rows from {results_path}")
    
    # Preprocessing
    # Rename ADAPT to Adapt for consistency
    if "ADAPT" in rippleNet_df.columns:
        rippleNet_df.rename(columns={"ADAPT": "Adapt"}, inplace=True)
        
    print("Columns:", rippleNet_df.columns.tolist())
    print("Threshold:", sorted(rippleNet_df["Threshold"].unique()))
    
    display(rippleNet_df.head())
else:
    print(f"File not found: {results_path}. Please run process_live_spikes.py first.")

Loaded 1092 rows from spikes\all_networks_metrics_ripplenet.csv
Columns: ['Session', 'Channel', 'Threshold', 'Model', 'TP', 'FP', 'FN', 'Precision', 'Recall', 'F1', 'Mean_Latency', 'Num_Spikes', 'Num_Ripples']
Threshold: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

,Session,Channel,Threshold,Model,TP,FP,FN,Precision,Recall,F1,Mean_Latency,Num_Spikes,Num_Ripples
0,2025-09-22_17-42-27,24,0.3,ripplenet_bidirectional_best_random_seed123,78,178,31,0.304688,0.715596,0.427397,35.347436,269,109
1,2025-09-22_17-42-27,24,0.3,ripplenet_bidirectional_best_random_seed456,78,158,31,0.330508,0.715596,0.452174,34.717949,244,109
2,2025-09-22_17-42-27,24,0.3,ripplenet_bidirectional_best_random_seed789,77,189,32,0.289474,0.706422,0.410667,30.353680,277,109
3,2025-09-22_17-42-27,24,0.3,ripplenet_bidirectional_random_seed123,66,99,43,0.400000,0.605505,0.481752,40.259091,171,109
4,2025-09-22_17-42-27,24,0.3,ripplenet_bidirectional_random_seed456,80,180,29,0.307692,0.733945,0.433604,32.437917,271,109

In [4]:
# Load Data
results_path = os.path.join("spikes", "all_networks_metrics_ripplAI.csv")

if os.path.exists(results_path):
    ripplAI_df = pd.read_csv(results_path)
    print(f"Loaded {len(ripplAI_df)} rows from {results_path}")
    
    # Preprocessing
    # Rename ADAPT to Adapt for consistency
    if "ADAPT" in ripplAI_df.columns:
        ripplAI_df.rename(columns={"ADAPT": "Adapt"}, inplace=True)
        
    print("Columns:", ripplAI_df.columns.tolist())
    print("Threshold:", sorted(ripplAI_df["Threshold"].unique()))
    
    display(ripplAI_df.head())
else:
    print(f"File not found: {results_path}. Please run process_live_spikes.py first.")

Loaded 2250 rows from spikes\all_networks_metrics_ripplAI.csv
Columns: ['Session', 'Channel', 'Threshold', 'Model', 'TP', 'FP', 'FN', 'Precision', 'Recall', 'F1', 'Mean_Latency', 'Num_Spikes', 'Num_Ripples']
Threshold: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]

,Session,Channel,Threshold,Model,TP,FP,FN,Precision,Recall,F1,Mean_Latency,Num_Spikes,Num_Ripples
0,2025-09-22_17-42-27,24,0.3,CNN1D_1,80,68,29,0.540541,0.733945,0.622568,14.054167,170,109
1,2025-09-22_17-42-27,24,0.3,CNN1D_2,36,1,73,0.972973,0.330275,0.493151,17.206481,37,109
2,2025-09-22_17-42-27,24,0.3,CNN1D_3,63,12,46,0.840000,0.577982,0.684783,12.385714,75,109
3,2025-09-22_17-42-27,24,0.3,CNN1D_4,56,10,53,0.848485,0.513761,0.640000,16.235714,67,109
4,2025-09-22_17-42-27,24,0.3,CNN1D_5,74,60,35,0.552239,0.678899,0.609053,7.547748,138,109

In [ ]:
# Load Data
results_path = os.path.join(os.pardir,"liset_test","cnn_detections", "all_networks_metrics_liset.csv")

if os.path.exists(results_path):
    liset_df = pd.read_csv(results_path)
    print(f"Loaded {len(liset_df)} rows from {results_path}")
    
    # Preprocessing
    # Rename ADAPT to Adapt for consistency
    if "ADAPT" in liset_df.columns:
        liset_df.rename(columns={"ADAPT": "Adapt"}, inplace=True)
        
    print("Columns:", liset_df.columns.tolist())
    print("Threshold:", sorted(liset_df["Threshold"].unique()))
    
    display(liset_df.head())
else:
    print(f"File not found: {results_path}. Please run process_live_spikes.py first.")

Loaded 60 rows from ..\liset_test\cnn_detections\all_networks_metrics_liset.csv
Columns: ['Session', 'Channel', 'Threshold', 'TP', 'FP', 'FN', 'Precision', 'Recall', 'F1', 'Mean_Latency', 'Num_Spikes', 'Num_Ripples']
Threshold: [0.3, 0.4, 0.5, 0.6, 0.7]

,Session,Channel,Threshold,TP,FP,FN,Precision,Recall,F1,Mean_Latency,Num_Spikes,Num_Ripples
0,2025-09-24_14-22-55,25,0.3,259,37,5,0.875000,0.981061,0.925000,7.943758,1561,264
1,2025-09-24_10-24-40,30,0.3,51,188,41,0.213389,0.554348,0.308157,22.577778,398,92
2,2025-09-25_12-52-22,25,0.3,14,196,34,0.066667,0.291667,0.108527,45.276190,682,48
3,2025-09-24_11-34-51,30,0.3,61,176,10,0.257384,0.859155,0.396104,18.681967,517,71
4,2025-09-24_15-13-10,14,0.3,59,6,25,0.907692,0.702381,0.791946,21.240678,162,84

In [ ]:
# Load SNN Data
# Load Data
results_path = os.path.join(os.pardir,"liset_test","cnn_detections", "all_networks_metrics_liset.csv")

if os.path.exists(results_path):
    liset_df = pd.read_csv(results_path)
    print(f"Loaded {len(liset_df)} rows from {results_path}")
    
    # Preprocessing
    # Rename ADAPT to Adapt for consistency
    if "ADAPT" in liset_df.columns:
        liset_df.rename(columns={"ADAPT": "Adapt"}, inplace=True)
        
    print("Columns:", liset_df.columns.tolist())
    print("Threshold:", sorted(liset_df["Threshold"].unique()))
    
    display(liset_df.head())
else:
    print(f"File not found: {results_path}. Please run process_live_spikes.py first.")